#!/bin/bash
DIR=$(dirname "$(realpath "$0")")
LIBS="$DIR/root/lib64"
BIN="$DIR/root/bin/intel_clc"

if [[ "${*}" ==  *' -I'* ]]; then
  exec env LD_LIBRARY_PATH="$LIBS:$LD_LIBRARY_PATH" "$LIBS/ld-linux-x86-64.so.2" "$BIN" "$@" -I"$DIR/root/include"
else
  exec env LD_LIBRARY_PATH="$LIBS:$LD_LIBRARY_PATH" "$LIBS/ld-linux-x86-64.so.2" "$BIN" "$@"
fi
